# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0001_added_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='path',
            new_name='full_path',
        ),
        migrations.AddField(
            model_name='file',
            name='relative_path',
            field=models.CharField(default='/', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(max_length=8),
        ),
    ]
