# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 00:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('downloads', '0003_added_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileSync',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.IntegerField(blank=True, null=True)),
                ('updated', models.IntegerField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField(blank=True, null=True)),
                ('previous_total', models.IntegerField(blank=True, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('started', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('finished', models.DateTimeField(blank=True, editable=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
