# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-17 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0004_added_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesync',
            name='finished',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
