# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-15 19:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0005_fixed_jobs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='size',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='filesync',
            name='size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
