# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('downloads', '0006_auto_20170515_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=40)),
                ('description', models.TextField()),
                ('groups', models.ManyToManyField(to='auth.Group')),
            ],
        ),
    ]
