# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0008_auto_20170529_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(max_length=255),
        ),
    ]
