# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-29 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('downloads', '0011_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(max_length=32),
        ),
    ]
